import torch
from torch.utils.data import Dataset
import scipy.io

class MatDataset(Dataset):
    """
    Loads Matlab .mat datasets generated by traditional solvers.
    """
    def __init__(self, file_path, x_key='x', y_key='y', num_samples=None):
        super(MatDataset, self).__init__()
        # Load .mat file
        mat_data = scipy.io.loadmat(file_path)
        
        x_data = mat_data[x_key]
        y_data = mat_data[y_key]
        
        # Convert to float PyTorch tensors
        self.x = torch.tensor(x_data, dtype=torch.float32)
        self.y = torch.tensor(y_data, dtype=torch.float32)
        
        if num_samples is not None:
            self.x = self.x[:num_samples]
            self.y = self.y[:num_samples]

    def __len__(self):
        return self.x.size(0)

    def __getitem__(self, idx):
        return self.x[idx], self.y[idx]
