import torch
from torch.utils.data import Dataset
import scipy.io

class MatDataset(Dataset):
    """
    Loads Matlab .mat datasets generated by traditional solvers.
    """
    def __init__(self, file_path, x_key='coeff', y_key='sol', num_samples=None, flatten_for_graph=False):
        super(MatDataset, self).__init__()
        
        # Load .mat file
        mat_data = scipy.io.loadmat(file_path)
        x_data = mat_data[x_key]
        y_data = mat_data[y_key]
        
        # Convert to float PyTorch tensors and add channel dimension
        # Assuming Darcy data shape: (num_samples, H, W) -> (num_samples, H, W, 1)
        self.x = torch.tensor(x_data, dtype=torch.float32).unsqueeze(-1)
        self.y = torch.tensor(y_data, dtype=torch.float32).unsqueeze(-1)
        
        if num_samples is not None:
            self.x = self.x[:num_samples]
            self.y = self.y[:num_samples]
            
        self.flatten_for_graph = flatten_for_graph
        if self.flatten_for_graph:
            # Flatten spatial dimensions for GNO/MGNO: (batch, num_nodes, 1)
            self.x = self.x.view(self.x.size(0), -1, self.x.size(-1))
            self.y = self.y.view(self.y.size(0), -1, self.y.size(-1))

    def __len__(self):
        return self.x.size(0)

    def __getitem__(self, idx):
        return self.x[idx], self.y[idx]


def get_grid2d(resolution, batch_size=1, device='cpu', flatten=False):
    """
    Generates a 2D coordinate grid for GNO/MGNO models.
    Coordinates are normalized to [0, 1].
    """
    ticks = torch.linspace(0, 1, resolution, device=device)
    grid_x, grid_y = torch.meshgrid(ticks, ticks, indexing='ij')
    
    # Shape: (resolution, resolution, 2)
    grid = torch.stack([grid_x, grid_y], dim=-1)
    
    if flatten:
        # Shape: (batch_size, num_nodes, 2)
        grid = grid.view(-1, 2).unsqueeze(0).repeat(batch_size, 1, 1)
    else:
        # Shape: (batch_size, resolution, resolution, 2)
        grid = grid.unsqueeze(0).repeat(batch_size, 1, 1, 1)
        
    return grid
